# Model arguments
model_name_or_path:  /code/models/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
preprocessing_num_workers: 12

# SFT trainer config
bf16: True
do_eval: False
eval_strategy: "no"
gradient_checkpointing: True
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: peval-qwen2.5-7b-sft
hub_strategy: every_save
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 5
output_dir: data/sft
overwrite_output_dir: True
learning_rate: 1.0e-05
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
push_to_hub: False
remove_unused_columns: True
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 50
save_total_limit: 12
seed: 42
warmup_ratio: 0.1